config/routes.rb
Imageboard::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :boards do
    resources :nodes
  end

  resources :nodes do
    resources :comments
  end
  
  match '/' => 'boards#index' 

end

app/models/node.rb
class Node < ActiveRecord::Base
  include ApplicationHelper
  validates :body, :picture, :presence => true
  
  has_many :comments, :order => "id ASC", :dependent => :destroy
  belongs_to :board
  mount_uploader :picture, PictureUploader
  before_create{
    |node|
    board = Board.find(node.board_id)
    node.ip = Thread.current[:request].remote_ip
    node.last_comment = Time.now # != creatd_at
    node.formated_date = Time.now.strftime("%d %b %Y, %H:%M")
    node.number = board.post_counter + 1
    board.post_counter += 1
    board.save
  }
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController  
  # GET /nodes
  # GET /nodes.json

  attr_accessor :board_list

  def index
    @nodes = Node.paginate(:page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @nodes }
    end
  end
  
  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @board_list = Board.all
    @node = Node.find(params[:id])
    #@node = Node.find_by_number(params[:id], params[:board_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    #@node = Node.find_by_number(params[:id], params[:board_id])
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    respond_to do |format|
      
      @board = Board.find(params[:board_id])
      @node = @board.nodes.create(params[:node])
      if @node.save
        format.html { redirect_to @node, :notice => 'Node was successfully created.' }
        format.json { render :json => @node, :status => :created, :location => @node }
      else
        # Пока такой костыль.
        format.html { redirect_to @board, :notice => 'There was some errors. Enter your message and choose a picture.' }
        format.json { render :json => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    #@node = Node.find_by_number(params[:id], params[:board_id])
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, :notice => 'Node was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    #@node = Node.find_by_number(params[:id], params[:board_id])
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :ok }
    end
  end

  
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_node.html.haml
%div.thread
  %div.head
    = node.head
    = node.formated_date
    №
    = node.number
  %div.pic= link_to( image_tag( node.picture_url(:thumb).to_s), node.picture_url) if node.picture?
  %div.text
    = parser(node.body)
  %div.foot
    Total comments:
    = node.comments.size
    = link_to 'Reply', node
    = #link_to 'Delete node', node, :confirm => 'Are you sure?', :method => :delete

- if node.comments.size == 1
  = render node.comments.last
- if node.comments.size == 2
  = render node.comments.limit(2).offset(node.comments.size - 2)
- if node.comments.size > 2
  = render node.comments.limit(3).offset(node.comments.size - 3)
%hr

app/views/nodes/index.html.haml
%h1 Nodes

= link_to 'New node', new_node_path
%hr
- @nodes.reverse.each do |node|
  %div.thread
    %table
      %tr
        %td= node.head
      %tr
        %td
          %div.picture= link_to( image_tag( node.picture_url(:thumb).to_s), node.picture_url) if node.picture?
          %div.body_text= simple_format(node.body)
    %table
      %td= node.id
      %td= node.board.name
      %td= node.created_at.strftime("%d %b %Y, %H:%M")
      %td  Comments:
      %td= node.comments.size
      %td= link_to 'Reply', node
      %td= #link_to 'Delete node', node, :confirm => 'Are you sure?', :method => :delete     
  %hr
%br
= will_paginate @nodes

app/views/nodes/show.html.haml
%p#notice= notice



=# render :partial => 'shared/form', :locals =>{:zone => @node, :content => @node.comments} # выводит лишние пустые комменты


%div.thread
  %div.head
    = @node.head
    = @node.formated_date
    №
    = @node.number
  %div.pic= link_to( image_tag( @node.picture_url(:thumb).to_s), @node.picture_url) if @node.picture?
  %div.text= parser(@node.body)   
  %div.foot
  //---------------
%h2 Comments:
= render @node.comments
%hr
%br

Create comment
= render :partial => 'shared/form', :locals => {:zone => @node, :content => @node.comments}
= link_to 'Back', board_path(@node.board)