config/routes.rb
Imageboard::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :boards do
    resources :nodes
  end

  resources :nodes do
    resources :comments
  end
  
  match '/' => 'boards#index' 

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :nodes, :order => "last_comment DESC", :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  before_create {
    |board|
    board.post_counter = 0 # Количество постов в свежесозданной доске - 0
  }

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.json
  #
  attr_accessor :board_list, :board_nodes
  $nodes_per_page = 10
  def index
    @board_list = Board.all
    @boards = Board.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board_list = Board.all
    @board = Board.find(params[:id])
    @board_nodes = @board.nodes.all
    # Пагинация, аттеншн - располагание тредов по убыванию даты последнего коммента происходит здесь,
    # поэтому нефиг пирать реверс в board/show
    @nodes = @board.nodes.paginate(:page => params[:page], :per_page => $nodes_per_page, :order => 'last_comment DESC')
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, :notice => 'Board was successfully created.' }
        format.json { render :json => @board, :status => :created, :location => @board }
      else
        format.html { render :action => "new" }
        format.json { render :json => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, :notice => 'Board was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.haml
=form_for ([@board, @board.nodes.build]) do |f|
  - @board.nodes.build.errors.full_messages.each do |msg|
    = msg
  %table.postform
    %tr
      %td
        = f.label :head
        = f.text_field :head, :class =>'headinput'
    %tr
      %td
        = f.label :body
        = f.text_area :body, :class => 'textarea'
    %tr
      %td
        = f.label :picture
        = f.file_field :picture
        = f.hidden_field :picture_cache
    %tr
      %td
        =f.submit 'Save'

app/views/boards/index.html.haml
%h1
  Welcome!

%h2 Full list of existing forums:
%ul.boardlist
  - @boards.each do |board|
    %li
      = board.name
      = link_to "Go", board
%br

app/views/boards/show.html.haml
%p#notice= notice



%h1
  %center= @board.name
%br

New node:

= render :partial => 'shared/form', :locals => {:zone => @board, :content => @board.nodes}

%h2 Nodes:

= render @nodes #reverse в контроллере

= will_paginate @nodes

= link_to 'Back', boards_path